"""autogenerated by genpy from haws/Conflict.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Conflict(genpy.Message):
  _md5sum = "01359ce202f254731c57b778944aa8d5"
  _type = "haws/Conflict"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool avoid_activated
float64 tc
float64 gamma

"""
  __slots__ = ['avoid_activated','tc','gamma']
  _slot_types = ['bool','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       avoid_activated,tc,gamma

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Conflict, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.avoid_activated is None:
        self.avoid_activated = False
      if self.tc is None:
        self.tc = 0.
      if self.gamma is None:
        self.gamma = 0.
    else:
      self.avoid_activated = False
      self.tc = 0.
      self.gamma = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B2d.pack(_x.avoid_activated, _x.tc, _x.gamma))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.avoid_activated, _x.tc, _x.gamma,) = _struct_B2d.unpack(str[start:end])
      self.avoid_activated = bool(self.avoid_activated)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B2d.pack(_x.avoid_activated, _x.tc, _x.gamma))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.avoid_activated, _x.tc, _x.gamma,) = _struct_B2d.unpack(str[start:end])
      self.avoid_activated = bool(self.avoid_activated)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B2d = struct.Struct("<B2d")
