/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/rafa/wsdift/src/haws/msg/Conflict.msg
 *
 */


#ifndef HAWS_MESSAGE_CONFLICT_H
#define HAWS_MESSAGE_CONFLICT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace haws
{
template <class ContainerAllocator>
struct Conflict_
{
  typedef Conflict_<ContainerAllocator> Type;

  Conflict_()
    : avoid_activated(false)
    , tc(0.0)  {
    }
  Conflict_(const ContainerAllocator& _alloc)
    : avoid_activated(false)
    , tc(0.0)  {
    }



   typedef uint8_t _avoid_activated_type;
  _avoid_activated_type avoid_activated;

   typedef double _tc_type;
  _tc_type tc;




  typedef boost::shared_ptr< ::haws::Conflict_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::haws::Conflict_<ContainerAllocator> const> ConstPtr;

}; // struct Conflict_

typedef ::haws::Conflict_<std::allocator<void> > Conflict;

typedef boost::shared_ptr< ::haws::Conflict > ConflictPtr;
typedef boost::shared_ptr< ::haws::Conflict const> ConflictConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::haws::Conflict_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::haws::Conflict_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace haws

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'haws': ['/home/rafa/wsdift/src/haws/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::haws::Conflict_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::haws::Conflict_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haws::Conflict_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haws::Conflict_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haws::Conflict_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haws::Conflict_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::haws::Conflict_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eeb3616bb5a522dd2c0241869fb7b7c6";
  }

  static const char* value(const ::haws::Conflict_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeeb3616bb5a522ddULL;
  static const uint64_t static_value2 = 0x2c0241869fb7b7c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::haws::Conflict_<ContainerAllocator> >
{
  static const char* value()
  {
    return "haws/Conflict";
  }

  static const char* value(const ::haws::Conflict_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::haws::Conflict_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool avoid_activated\n\
float64 tc\n\
";
  }

  static const char* value(const ::haws::Conflict_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::haws::Conflict_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.avoid_activated);
      stream.next(m.tc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Conflict_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::haws::Conflict_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::haws::Conflict_<ContainerAllocator>& v)
  {
    s << indent << "avoid_activated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.avoid_activated);
    s << indent << "tc: ";
    Printer<double>::stream(s, indent + "  ", v.tc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAWS_MESSAGE_CONFLICT_H
