######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 21 15:11:48 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += project.cpp
